### ISSUE TITLE
Image width and height

### ISSUE THREAD

**Issue by Mayank4884** [openPupil/Open-PupilEXT#33]
### Discussed in https://github.com/openPupil/Open-PupilEXT/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **Mayank4884** December  8, 2022</sup>
Even if I am Changing the image width and height in the pupil settings.. Why there is no change in the pupil diameter? </div>

**Comment by BZandi** [comment]
Repeated question. See here https://github.com/openPupil/Open-PupilEXT/discussions/32
